### ISSUE TITLE
安装时报错

### ISSUE THREAD

**Issue by kissjin** [rayylee/keypress#5]
![image](https://user-images.githubusercontent.com/40197934/152970211-32387f86-1500-4987-9f37-3d8c34ca45c1.png)
这是什么原因呀
这是rust版本
![image](https://user-images.githubusercontent.com/40197934/152970383-18ed36c8-9b25-4c1c-a5f8-3fed0ab81d00.png)

**Comment by hburaylee** [comment]
> ![image](https://user-images.githubusercontent.com/40197934/152970211-32387f86-1500-4987-9f37-3d8c34ca45c1.png) 这是什么原因呀 这是rust版本 ![image](https://user-images.githubusercontent.com/40197934/152970383-18ed36c8-9b25-4c1c-a5f8-3fed0ab81d00.png)

设置了国内代理源了吗？在$HOME/.cargo/下建立一个config文件，加入如下配置
```
[source.crates-io]
replace-with = 'tuna'

[source.tuna]
registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"
```
